<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GiaoVienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('giao_viens')->delete();

        DB::table('giao_viens')->truncate();

        DB::table('giao_viens')->insert([
            [
                'id' => 1,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Nguyễn Hoàng Phương',
                'so_dien_thoai' => '0912345678',
                'email' => 'kuem271003@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1, // 0: Nữ, 1: Nam
                'trinh_do' => 2, // 0: Trung cấp, 1: Cao đẳng, 2: Đại học, 3: Sau đại học
                'chuyen_mon' => 'Toán học',
                'dia_chi' => 'Hà Nội',
                'ngay_sinh' => '1985-03-15',
                'avatar' => 'https://example.com/avatar_gv1.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 2,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Trần Văn Minh',
                'so_dien_thoai' => '0987654321',
                'email' => 'minh.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Ngữ văn',
                'dia_chi' => 'TP. Hồ Chí Minh',
                'ngay_sinh' => '1982-07-20',
                'avatar' => 'https://example.com/avatar_gv2.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 3,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Lê Thị Hương',
                'so_dien_thoai' => '0901234567',
                'email' => 'huong.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 3,
                'chuyen_mon' => 'Tiếng Anh',
                'dia_chi' => 'Đà Nẵng',
                'ngay_sinh' => '1988-11-10',
                'avatar' => 'https://example.com/avatar_gv3.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 4,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Phạm Quang Dũng',
                'so_dien_thoai' => '0923456789',
                'email' => 'dung.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Vật lý',
                'dia_chi' => 'Hải Phòng',
                'ngay_sinh' => '1980-05-25',
                'avatar' => 'https://example.com/avatar_gv4.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 5,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Đỗ Thị Mai',
                'so_dien_thoai' => '0934567890',
                'email' => 'mai.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 2,
                'chuyen_mon' => 'Hóa học',
                'dia_chi' => 'Cần Thơ',
                'ngay_sinh' => '1987-09-12',
                'avatar' => 'https://example.com/avatar_gv5.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 6,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Vũ Văn Thành',
                'so_dien_thoai' => '0945678901',
                'email' => 'thanh.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 1,
                'chuyen_mon' => 'Sinh học',
                'dia_chi' => 'Huế',
                'ngay_sinh' => '1984-12-08',
                'avatar' => 'https://example.com/avatar_gv6.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 7,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Hoàng Thị Linh',
                'so_dien_thoai' => '0956789012',
                'email' => 'linh.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 2,
                'chuyen_mon' => 'Lịch sử',
                'dia_chi' => 'Nha Trang',
                'ngay_sinh' => '1986-02-18',
                'avatar' => 'https://example.com/avatar_gv7.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 8,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Bùi Minh Tuấn',
                'so_dien_thoai' => '0967890123',
                'email' => 'tuan.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 3,
                'chuyen_mon' => 'Địa lý',
                'dia_chi' => 'Vũng Tàu',
                'ngay_sinh' => '1983-06-30',
                'avatar' => 'https://example.com/avatar_gv8.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 9,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Ngô Thị Hạnh',
                'so_dien_thoai' => '0978901234',
                'email' => 'hanh.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 2,
                'chuyen_mon' => 'Giáo dục công dân',
                'dia_chi' => 'Quy Nhon',
                'ngay_sinh' => '1989-04-14',
                'avatar' => 'https://example.com/avatar_gv9.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 10,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Đinh Văn Hòa',
                'so_dien_thoai' => '0989012345',
                'email' => 'hoa.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Thể dục',
                'dia_chi' => 'Vinh',
                'ngay_sinh' => '1981-10-22',
                'avatar' => 'https://example.com/avatar_gv10.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 11,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Lý Thị Phương',
                'so_dien_thoai' => '0990123456',
                'email' => 'phuong.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 3,
                'chuyen_mon' => 'Âm nhạc',
                'dia_chi' => 'Thái Nguyên',
                'ngay_sinh' => '1990-01-05',
                'avatar' => 'https://example.com/avatar_gv11.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 12,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Trịnh Quang Nam',
                'so_dien_thoai' => '0901234568',
                'email' => 'nam.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Mỹ thuật',
                'dia_chi' => 'Bắc Giang',
                'ngay_sinh' => '1985-08-17',
                'avatar' => 'https://example.com/avatar_gv12.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 13,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Cao Thị Thu',
                'so_dien_thoai' => '0912345679',
                'email' => 'thu.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 1,
                'chuyen_mon' => 'Tin học',
                'dia_chi' => 'Nam Định',
                'ngay_sinh' => '1992-12-03',
                'avatar' => 'https://example.com/avatar_gv13.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 14,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Phan Văn Long',
                'so_dien_thoai' => '0923456780',
                'email' => 'long.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Công nghệ',
                'dia_chi' => 'Hà Nam',
                'ngay_sinh' => '1979-03-28',
                'avatar' => 'https://example.com/avatar_gv14.jpg',
                'is_block' => 1, // Tài khoản bị khóa
                'tinh_trang' => 0, // Không hoạt động
            ],
            [
                'id' => 15,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Đặng Thị Yến',
                'so_dien_thoai' => '0934567891',
                'email' => 'yen.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 3,
                'chuyen_mon' => 'Tâm lý học',
                'dia_chi' => 'Bắc Ninh',
                'ngay_sinh' => '1991-07-11',
                'avatar' => 'https://example.com/avatar_gv15.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 16,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Nguyễn Văn Đức',
                'so_dien_thoai' => '0945678901',
                'email' => 'duc.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Toán học',
                'dia_chi' => 'Hà Nội',
                'ngay_sinh' => '1987-03-15',
                'avatar' => 'https://example.com/avatar_gv16.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 17,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Trần Thị Lan',
                'so_dien_thoai' => '0956789012',
                'email' => 'lan.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 2,
                'chuyen_mon' => 'Ngữ văn',
                'dia_chi' => 'TP. Hồ Chí Minh',
                'ngay_sinh' => '1989-07-20',
                'avatar' => 'https://example.com/avatar_gv17.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 18,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Lê Văn Hùng',
                'so_dien_thoai' => '0967890123',
                'email' => 'hung.gv@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 3,
                'chuyen_mon' => 'Tiếng Anh',
                'dia_chi' => 'Đà Nẵng',
                'ngay_sinh' => '1986-11-10',
                'avatar' => 'https://example.com/avatar_gv18.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 19,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Phạm Thị Mai',
                'so_dien_thoai' => '0978901234',
                'email' => 'mai.gv2@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 0,
                'trinh_do' => 2,
                'chuyen_mon' => 'Vật lý',
                'dia_chi' => 'Hải Phòng',
                'ngay_sinh' => '1988-05-25',
                'avatar' => 'https://example.com/avatar_gv19.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 20,
                'id_chuc_vu' => 3,
                'ho_va_ten' => 'Đỗ Văn Nam',
                'so_dien_thoai' => '0989012345',
                'email' => 'nam.gv2@gmail.com',
                'password' => bcrypt('123456'),
                'gioi_tinh' => 1,
                'trinh_do' => 2,
                'chuyen_mon' => 'Hóa học',
                'dia_chi' => 'Cần Thơ',
                'ngay_sinh' => '1985-09-12',
                'avatar' => 'https://example.com/avatar_gv20.jpg',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
        ]);
    }
}
