<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class NhanVienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('nhan_viens')->delete();

        DB::table('nhan_viens')->truncate();

        DB::table('nhan_viens')->insert([
            [
                'id' => 1,
                'ho_va_ten' => 'admin',
                'so_dien_thoai' => '0982078899',
                'email' => 'admin@gmail.com',
                'dia_chi' => 'Hà Nội',
                'id_chuc_vu' => 1,
                'avatar' => 'https://example.com/avatar1.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1990-01-15',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 2,
                'ho_va_ten' => 'Trần Thị Mai',
                'so_dien_thoai' => '0973245112',
                'email' => 'maitran@gmail.com',
                'dia_chi' => 'Đà Nẵng',
                'id_chuc_vu' => 2,
                'avatar' => 'https://example.com/avatar2.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1989-06-12',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 3,
                'ho_va_ten' => 'Lê Văn Hùng',
                'so_dien_thoai' => '0912345678',
                'email' => 'hunglv@gmail.com',
                'dia_chi' => 'TP. Hồ Chí Minh',
                'id_chuc_vu' => 3,
                'avatar' => 'https://example.com/avatar3.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1992-08-10',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 4,
                'ho_va_ten' => 'Phạm Thị Hạnh',
                'so_dien_thoai' => '0905123789',
                'email' => 'hanhpham@gmail.com',
                'dia_chi' => 'Huế',
                'id_chuc_vu' => 4,
                'avatar' => 'https://example.com/avatar4.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1995-03-25',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 5,
                'ho_va_ten' => 'Đỗ Quang Dũng',
                'so_dien_thoai' => '0988123123',
                'email' => 'dungdq@gmail.com',
                'dia_chi' => 'Quảng Ninh',
                'id_chuc_vu' => 5,
                'avatar' => 'https://example.com/avatar5.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1991-11-01',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 6,
                'ho_va_ten' => 'Nguyễn Thị Bích',
                'so_dien_thoai' => '0967234567',
                'email' => 'bichnt@gmail.com',
                'dia_chi' => '1 Định',
                'id_chuc_vu' => 6,
                'avatar' => 'https://example.com/avatar6.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1993-09-09',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 7,
                'ho_va_ten' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0938222111',
                'email' => 'tuanle@gmail.com',
                'dia_chi' => 'Nghệ An',
                'id_chuc_vu' => 7,
                'avatar' => 'https://example.com/avatar7.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1987-12-25',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 8,
                'ho_va_ten' => 'Vũ Hồng Nhung',
                'so_dien_thoai' => '0944332211',
                'email' => 'nhungvu@gmail.com',
                'dia_chi' => 'Thái Bình',
                'id_chuc_vu' => 8,
                'avatar' => 'https://example.com/avatar8.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1994-02-18',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 9,
                'ho_va_ten' => 'Đặng Văn Long',
                'so_dien_thoai' => '0923456789',
                'email' => 'longdv@gmail.com',
                'dia_chi' => 'Phú Thọ',
                'id_chuc_vu' => 9,
                'avatar' => 'https://example.com/avatar9.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1988-07-07',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 10,
                'ho_va_ten' => 'Lý Thị Lệ',
                'so_dien_thoai' => '0911552334',
                'email' => 'lely@gmail.com',
                'dia_chi' => 'Vĩnh Phúc',
                'id_chuc_vu' => 10,
                'avatar' => 'https://example.com/avatar10.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1996-10-10',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            // Thêm 10 nhân viên khác
            [
                'id' => 11,
                'ho_va_ten' => 'Nguyễn Văn Bình',
                'so_dien_thoai' => '0909234567',
                'email' => 'binhnv@gmail.com',
                'dia_chi' => 'Bắc Giang',
                'id_chuc_vu' => 1,
                'avatar' => 'https://example.com/avatar11.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1993-03-15',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 12,
                'ho_va_ten' => 'Trịnh Thị Hoa',
                'so_dien_thoai' => '0977456123',
                'email' => 'hoatrinh@gmail.com',
                'dia_chi' => 'Tuyên Quang',
                'id_chuc_vu' => 2,
                'avatar' => 'https://example.com/avatar12.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1986-05-05',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 13,
                'ho_va_ten' => 'Phan Văn Cường',
                'so_dien_thoai' => '0933445566',
                'email' => 'cuongpv@gmail.com',
                'dia_chi' => 'Ninh Bình',
                'id_chuc_vu' => 3,
                'avatar' => 'https://example.com/avatar13.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1990-09-19',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 14,
                'ho_va_ten' => 'Đỗ Thanh Tâm',
                'so_dien_thoai' => '0955337766',
                'email' => 'tamdt@gmail.com',
                'dia_chi' => 'Hải Phòng',
                'id_chuc_vu' => 4,
                'avatar' => 'https://example.com/avatar14.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1991-01-23',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 15,
                'ho_va_ten' => 'Ngô Quang Huy',
                'so_dien_thoai' => '0901231234',
                'email' => 'huyngo@gmail.com',
                'dia_chi' => 'Bắc Ninh',
                'id_chuc_vu' => 5,
                'avatar' => 'https://example.com/avatar15.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1985-11-30',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 16,
                'ho_va_ten' => 'Trần Thu Hà',
                'so_dien_thoai' => '0967896543',
                'email' => 'hatt@gmail.com',
                'dia_chi' => 'Thanh Hóa',
                'id_chuc_vu' => 6,
                'avatar' => 'https://example.com/avatar16.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1997-04-22',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 17,
                'ho_va_ten' => 'Bùi Đức Anh',
                'so_dien_thoai' => '0978654321',
                'email' => 'anhbui@gmail.com',
                'dia_chi' => 'Hòa Bình',
                'id_chuc_vu' => 7,
                'avatar' => 'https://example.com/avatar17.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1994-06-14',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 18,
                'ho_va_ten' => 'Nguyễn Thị Lụa',
                'so_dien_thoai' => '0934789123',
                'email' => 'luant@gmail.com',
                'dia_chi' => 'Lào Cai',
                'id_chuc_vu' => 8,
                'avatar' => 'https://example.com/avatar18.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1990-08-08',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 19,
                'ho_va_ten' => 'Hồ Thanh Sơn',
                'so_dien_thoai' => '0912876543',
                'email' => 'sonht@gmail.com',
                'dia_chi' => 'Quảng Ngãi',
                'id_chuc_vu' => 9,
                'avatar' => 'https://example.com/avatar19.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1989-07-07',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 20,
                'ho_va_ten' => 'Lương Thị Thu',
                'so_dien_thoai' => '0987654321',
                'email' => 'thuluong@gmail.com',
                'dia_chi' => 'Yên Bái',
                'id_chuc_vu' => 10,
                'avatar' => 'https://example.com/avatar20.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1995-12-12',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
        ]);
    }
}
