<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class NhanVienSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('nhan_viens')->delete();

        DB::table('nhan_viens')->truncate();

        DB::table('nhan_viens')->insert([
            [
                'id' => 1,
                'ho_va_ten' => 'admin',
                'so_dien_thoai' => '0982078899',
                'email' => 'admin@gmail.com',
                'dia_chi' => 'Hà Nội',
                'id_chuc_vu' => 1,
                'avatar' => 'https://i.pinimg.com/1200x/13/c2/9e/13c29eee725ec2125487ddf0cf119c3c.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1990-01-15',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 2,
                'ho_va_ten' => 'Trần Thị Mai',
                'so_dien_thoai' => '0973245112',
                'email' => 'maitran@gmail.com',
                'dia_chi' => 'Đà Nẵng',
                'id_chuc_vu' => 2,
                'avatar' => 'https://i.pinimg.com/736x/22/7c/6f/227c6f105bc8f9cc743f334d651c99a1.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1989-06-12',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 3,
                'ho_va_ten' => 'Lê Văn Hùng',
                'so_dien_thoai' => '0912345678',
                'email' => 'hunglv@gmail.com',
                'dia_chi' => 'TP. Hồ Chí Minh',
                'id_chuc_vu' => 3,
                'avatar' => 'https://i.pinimg.com/1200x/d7/15/d6/d715d69594b07dc3e9d47209e8576a79.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1992-08-10',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 4,
                'ho_va_ten' => 'Phạm Thị Hạnh',
                'so_dien_thoai' => '0905123789',
                'email' => 'hanhpham@gmail.com',
                'dia_chi' => 'Huế',
                'id_chuc_vu' => 4,
                'avatar' => 'https://i.pinimg.com/736x/8a/0d/78/8a0d7882ebf0f2adf05fb17eebfa343f.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1995-03-25',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 5,
                'ho_va_ten' => 'Đỗ Quang Dũng',
                'so_dien_thoai' => '0988123123',
                'email' => 'dungdq@gmail.com',
                'dia_chi' => 'Quảng Ninh',
                'id_chuc_vu' => 5,
                'avatar' => 'https://i.pinimg.com/736x/28/af/bc/28afbc0f8b003a11ad93a5d16262197b.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1991-11-01',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 6,
                'ho_va_ten' => 'Nguyễn Thị Bích',
                'so_dien_thoai' => '0967234567',
                'email' => 'bichnt@gmail.com',
                'dia_chi' => '1 Định',
                'id_chuc_vu' => 6,
                'avatar' => 'https://i.pinimg.com/736x/07/e2/e8/07e2e888237c15951800eb34d754eb7b.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1993-09-09',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 7,
                'ho_va_ten' => 'Lê Minh Tuấn',
                'so_dien_thoai' => '0938222111',
                'email' => 'tuanle@gmail.com',
                'dia_chi' => 'Nghệ An',
                'id_chuc_vu' => 7,
                'avatar' => 'https://i.pinimg.com/736x/7c/71/cb/7c71cb9f931f28522f4ffcfeb402b0e2.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1987-12-25',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 8,
                'ho_va_ten' => 'Vũ Hồng Nhung',
                'so_dien_thoai' => '0944332211',
                'email' => 'nhungvu@gmail.com',
                'dia_chi' => 'Thái Bình',
                'id_chuc_vu' => 8,
                'avatar' => 'https://i.pinimg.com/1200x/b7/6e/73/b76e738e9268dd9765e807dabf8fbc35.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1994-02-18',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 9,
                'ho_va_ten' => 'Đặng Văn Long',
                'so_dien_thoai' => '0923456789',
                'email' => 'longdv@gmail.com',
                'dia_chi' => 'Phú Thọ',
                'id_chuc_vu' => 9,
                'avatar' => 'https://i.pinimg.com/1200x/d4/6c/e9/d46ce940b1b2dfa791f3871a35d8a7ad.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1988-07-07',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 10,
                'ho_va_ten' => 'Lý Thị Lệ',
                'so_dien_thoai' => '0911552334',
                'email' => 'lely@gmail.com',
                'dia_chi' => 'Vĩnh Phúc',
                'id_chuc_vu' => 10,
                'avatar' => 'https://i.pinimg.com/1200x/02/b8/d1/02b8d1b1cebfea32e59907489381f442.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1996-10-10',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            // Thêm 10 nhân viên khác
            [
                'id' => 11,
                'ho_va_ten' => 'Nguyễn Văn Bình',
                'so_dien_thoai' => '0909234567',
                'email' => 'binhnv@gmail.com',
                'dia_chi' => 'Bắc Giang',
                'id_chuc_vu' => 1,
                'avatar' => 'https://i.pinimg.com/736x/8c/9d/b9/8c9db983009ba39a3e8e9c63f70812f2.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1993-03-15',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 12,
                'ho_va_ten' => 'Trịnh Thị Hoa',
                'so_dien_thoai' => '0977456123',
                'email' => 'hoatrinh@gmail.com',
                'dia_chi' => 'Tuyên Quang',
                'id_chuc_vu' => 2,
                'avatar' => 'https://i.pinimg.com/736x/80/88/27/808827ed74b4b3fa160c83c7a6612218.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1986-05-05',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 13,
                'ho_va_ten' => 'Phan Văn Cường',
                'so_dien_thoai' => '0933445566',
                'email' => 'cuongpv@gmail.com',
                'dia_chi' => 'Ninh Bình',
                'id_chuc_vu' => 3,
                'avatar' => 'https://i.pinimg.com/736x/22/7c/6f/227c6f105bc8f9cc743f334d651c99a1.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1990-09-19',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 14,
                'ho_va_ten' => 'Đỗ Thanh Tâm',
                'so_dien_thoai' => '0955337766',
                'email' => 'tamdt@gmail.com',
                'dia_chi' => 'Hải Phòng',
                'id_chuc_vu' => 4,
                'avatar' => 'https://i.pinimg.com/1200x/19/46/60/19466061f2ae5a7d2bc7d5f4de7b54a4.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1991-01-23',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 15,
                'ho_va_ten' => 'Ngô Quang Huy',
                'so_dien_thoai' => '0901231234',
                'email' => 'huyngo@gmail.com',
                'dia_chi' => 'Bắc Ninh',
                'id_chuc_vu' => 5,
                'avatar' => 'https://i.pinimg.com/1200x/19/46/60/19466061f2ae5a7d2bc7d5f4de7b54a4.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1985-11-30',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 16,
                'ho_va_ten' => 'Trần Thu Hà',
                'so_dien_thoai' => '0967896543',
                'email' => 'hatt@gmail.com',
                'dia_chi' => 'Thanh Hóa',
                'id_chuc_vu' => 6,
                'avatar' => 'https://i.pinimg.com/736x/92/58/89/92588973c91dcfc5677133dd019960d2.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1997-04-22',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 17,
                'ho_va_ten' => 'Bùi Đức Anh',
                'so_dien_thoai' => '0978654321',
                'email' => 'anhbui@gmail.com',
                'dia_chi' => 'Hòa Bình',
                'id_chuc_vu' => 7,
                'avatar' => 'https://i.pinimg.com/736x/a7/e7/38/a7e7385c7e4a70a2c7aab315c04c08d0.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1994-06-14',
                'is_block' => 1,
                'tinh_trang' => 0,
            ],
            [
                'id' => 18,
                'ho_va_ten' => 'Nguyễn Thị Lụa',
                'so_dien_thoai' => '0934789123',
                'email' => 'luant@gmail.com',
                'dia_chi' => 'Lào Cai',
                'id_chuc_vu' => 8,
                'avatar' => 'https://i.pinimg.com/736x/b3/e9/ca/b3e9ca19ba256a95c4129ab93cc5162c.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1990-08-08',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 19,
                'ho_va_ten' => 'Hồ Thanh Sơn',
                'so_dien_thoai' => '0912876543',
                'email' => 'sonht@gmail.com',
                'dia_chi' => 'Quảng Ngãi',
                'id_chuc_vu' => 9,
                'avatar' => 'https://i.pinimg.com/736x/86/73/1f/86731f8d412115ba1de9dbf3ab8f9b2b.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '1',
                'ngay_sinh' => '1989-07-07',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
            [
                'id' => 20,
                'ho_va_ten' => 'Lương Thị Thu',
                'so_dien_thoai' => '0987654321',
                'email' => 'thuluong@gmail.com',
                'dia_chi' => 'Yên Bái',
                'id_chuc_vu' => 10,
                'avatar' => 'https://i.pinimg.com/1200x/5b/1a/39/5b1a39f1f78494b6f3ffc8401273864c.jpg',
                'password' => bcrypt('123456'),
                'gioi_tinh' => '0',
                'ngay_sinh' => '1995-12-12',
                'is_block' => 0,
                'tinh_trang' => 1,
            ],
        ]);
    }
}
