<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhuHuynhSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('phu_huynhs')->delete();
        DB::table('phu_huynhs')->truncate();

        // Tạo 250 phụ huynh cho 500 học sinh (mỗi phụ huynh có 2-3 học sinh)
        $parentCount = 250; // Đủ cho 500 học sinh với tỷ lệ 2-3 học sinh/phụ huynh

        $lastNames = ['Nguyễn', 'Trần', 'Lê', 'Phạm', 'Hoàng', 'Đặng', 'Vũ', 'Ngô', 'Trịnh', 'Lương', 'Phan', 'Bùi', 'Đỗ', 'Hà', 'Đinh', 'Trương', 'Tạ', 'Phùng', 'Lý', 'Mai', 'Tô', 'Đinh', 'Ngô', 'Lương'];
        $middleNames = ['Văn', 'Thị'];
        $firstNames = [
            'An',
            'Bích',
            'Châu',
            'Dung',
            'Đạt',
            'Hồng',
            'Quân',
            'Lan',
            'Hùng',
            'Mai',
            'Lâm',
            'Mơ',
            'Nam',
            'Ngọc',
            'Phúc',
            'Quỳnh',
            'Sơn',
            'Thanh',
            'Thắng',
            'Thảo',
            'Toàn',
            'Trang',
            'Tuấn',
            'Vân',
            'Việt',
            'Yến',
            'Bình',
            'Cúc',
            'Dũng',
            'Giang',
            'Hiếu',
            'Hòa',
            'Huy',
            'Hương',
            'Khánh',
            'Kim',
            'Long',
            'Loan',
            'Lộc',
            'Mạnh',
            'Nga',
            'Phong',
            'Quý',
            'Quyên',
            'Thắm',
            'Thành',
            'Thu',
            'Bảo',
            'Cường',
            'Dương',
            'Đức',
            'Hạnh',
            'Hoa',
            'Khang',
            'Linh',
            'Minh',
            'Oanh',
            'Phương',
            'Quang',
            'Sinh',
            'Tâm',
            'Uyên',
            'Vinh',
            'Xuân',
            'Yên',
            'Chi',
            'Đan',
            'Em',
            'Gia',
            'Hân'
        ];

        $jobs = [
            'Giáo viên',
            'Kỹ sư',
            'Nhân viên văn phòng',
            'Tài xế',
            'Kế toán',
            'Bác sĩ',
            'Nội trợ',
            'Thợ điện',
            'Y tá',
            'Công nhân',
            'Buôn bán',
            'IT',
            'Công chức',
            'Kỹ thuật viên',
            'Tự do',
            'Kinh doanh',
            'Luật sư',
            'Bảo vệ',
            'Thợ may',
            'Nông dân'
        ];

        $cities = [
            'Hà Nội',
            'TP HCM',
            'Đà Nẵng',
            'Cần Thơ',
            'Hải Phòng',
            'Bắc Ninh',
            'Nam Định',
            'Quảng Ninh',
            'Thanh Hóa',
            'Nghệ An',
            'Hà Tĩnh',
            'Thái Bình',
            'Huế',
            'Vũng Tàu',
            'Lâm Đồng',
            'Hưng Yên',
            'Bình Dương',
            'Phú Thọ',
            'Bình Phước'
        ];

        $relationships = ['Bố', 'Mẹ', 'Anh', 'Chị', 'Cô', 'Chú', 'Bác', 'Cậu', 'Dì'];

        $parents = [];

        for ($i = 1; $i <= $parentCount; $i++) {
            $lastName = $lastNames[array_rand($lastNames)];
            $middleName = $middleNames[array_rand($middleNames)];
            $firstName = $firstNames[array_rand($firstNames)];
            $fullName = $lastName . ' ' . $middleName . ' ' . $firstName;
            $gender = ($middleName === 'Văn') ? 'Nam' : 'Nữ';

            // Tạo số điện thoại ngẫu nhiên
            $phone = '0' . rand(3, 9) . rand(10000000, 99999999);

            // Tạo email dựa trên tên (không dấu)
            $email = $this->removeVietnameseAccents(strtolower(str_replace(' ', '', $fullName))) . rand(1, 999) . '@example.com';

            // Ngày sinh từ 1970-1990
            $birthYear = rand(1970, 1990);
            $birthMonth = rand(1, 12);
            $birthDay = rand(1, 28);
            $birthDate = sprintf('%04d-%02d-%02d', $birthYear, $birthMonth, $birthDay);

            $parents[] = [
                'id' => $i,
                'ho_va_ten' => $fullName,
                'so_dien_thoai' => $phone,
                'email' => $email,
                'dia_chi' => $cities[array_rand($cities)],
                'quan_he' => $relationships[array_rand($relationships)],
                'password' => bcrypt('123456'), // Mã hóa password
                'gioi_tinh' => $gender,
                'nghe_nghiep' => $jobs[array_rand($jobs)],
                'ngay_sinh' => $birthDate,
                'is_block' => rand(1, 20) == 1 ? 1 : 0, // 5% bị khóa
                'is_active' => rand(1, 10) <= 9 ? 1 : 0, // 90% hoạt động
                'hash_reset' => null,
            ];
        }

        DB::table('phu_huynhs')->insert($parents);
    }

    /**
     * Loại bỏ dấu tiếng Việt
     */
    private function removeVietnameseAccents($str)
    {
        $accents = [
            'à',
            'á',
            'ạ',
            'ả',
            'ã',
            'â',
            'ầ',
            'ấ',
            'ậ',
            'ẩ',
            'ẫ',
            'ă',
            'ằ',
            'ắ',
            'ặ',
            'ẳ',
            'ẵ',
            'è',
            'é',
            'ẹ',
            'ẻ',
            'ẽ',
            'ê',
            'ề',
            'ế',
            'ệ',
            'ể',
            'ễ',
            'ì',
            'í',
            'ị',
            'ỉ',
            'ĩ',
            'ò',
            'ó',
            'ọ',
            'ỏ',
            'õ',
            'ô',
            'ồ',
            'ố',
            'ộ',
            'ổ',
            'ỗ',
            'ơ',
            'ờ',
            'ớ',
            'ợ',
            'ở',
            'ỡ',
            'ù',
            'ú',
            'ụ',
            'ủ',
            'ũ',
            'ư',
            'ừ',
            'ứ',
            'ự',
            'ử',
            'ữ',
            'ỳ',
            'ý',
            'ỵ',
            'ỷ',
            'ỹ',
            'đ',
            'À',
            'Á',
            'Ạ',
            'Ả',
            'Ã',
            'Â',
            'Ầ',
            'Ấ',
            'Ậ',
            'Ẩ',
            'Ẫ',
            'Ă',
            'Ằ',
            'Ắ',
            'Ặ',
            'Ẳ',
            'Ẵ',
            'È',
            'É',
            'Ẹ',
            'Ẻ',
            'Ẽ',
            'Ê',
            'Ề',
            'Ế',
            'Ệ',
            'Ể',
            'Ễ',
            'Ì',
            'Í',
            'Ị',
            'Ỉ',
            'Ĩ',
            'Ò',
            'Ó',
            'Ọ',
            'Ỏ',
            'Õ',
            'Ô',
            'Ồ',
            'Ố',
            'Ộ',
            'Ổ',
            'Ỗ',
            'Ơ',
            'Ờ',
            'Ớ',
            'Ợ',
            'Ở',
            'Ỡ',
            'Ù',
            'Ú',
            'Ụ',
            'Ủ',
            'Ũ',
            'Ư',
            'Ừ',
            'Ứ',
            'Ự',
            'Ử',
            'Ữ',
            'Ỳ',
            'Ý',
            'Ỵ',
            'Ỷ',
            'Ỹ',
            'Đ'
        ];

        $noAccents = [
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'i',
            'i',
            'i',
            'i',
            'i',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'y',
            'y',
            'y',
            'y',
            'y',
            'd',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'I',
            'I',
            'I',
            'I',
            'I',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'Y',
            'Y',
            'Y',
            'Y',
            'Y',
            'D'
        ];

        return str_replace($accents, $noAccents, $str);
    }
}
