name: Security Scan

on:
  push:
    branches: [ main, develop, master ]
  pull_request:
    branches: [ main, develop, master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate || true
          echo "Audit completed. Check output above for vulnerabilities."

      - name: Check for known vulnerabilities
        run: |
          if command -v npm-audit-resolver &> /dev/null; then
            npm-audit-resolver
          else
            echo "npm-audit-resolver not installed, skipping..."
          fi
        continue-on-error: true

